[ Skip to content ](https://ai.pydantic.dev/api/exceptions/<#pydantic_aiexceptions>)
[ ![logo](https://ai.pydantic.dev/img/logo-white.svg) ](https://ai.pydantic.dev/api/exceptions/<../..> "PydanticAI")
PydanticAI 
pydantic_ai.exceptions 
Type to start searching
[ pydantic/pydantic-ai  ](https://ai.pydantic.dev/api/exceptions/<https:/github.com/pydantic/pydantic-ai> "Go to repository")
[ ![logo](https://ai.pydantic.dev/img/logo-white.svg) ](https://ai.pydantic.dev/api/exceptions/<../..> "PydanticAI") PydanticAI 
[ pydantic/pydantic-ai  ](https://ai.pydantic.dev/api/exceptions/<https:/github.com/pydantic/pydantic-ai> "Go to repository")
  * [ Introduction  ](https://ai.pydantic.dev/api/exceptions/<../..>)
  * [ Installation  ](https://ai.pydantic.dev/api/exceptions/install/>)
  * [ Getting Help  ](https://ai.pydantic.dev/api/exceptions/help/>)
  * [ Contributing  ](https://ai.pydantic.dev/api/exceptions/contributing/>)
  * [ Troubleshooting  ](https://ai.pydantic.dev/api/exceptions/troubleshooting/>)
  * Documentation  Documentation 
    * [ Agents  ](https://ai.pydantic.dev/api/exceptions/agents/>)
    * [ Models  ](https://ai.pydantic.dev/api/exceptions/models/>)
    * [ Dependencies  ](https://ai.pydantic.dev/api/exceptions/dependencies/>)
    * [ Function Tools  ](https://ai.pydantic.dev/api/exceptions/tools/>)
    * [ Common Tools  ](https://ai.pydantic.dev/api/exceptions/common_tools/>)
    * [ Results  ](https://ai.pydantic.dev/api/exceptions/results/>)
    * [ Messages and chat history  ](https://ai.pydantic.dev/api/exceptions/message-history/>)
    * [ Testing and Evals  ](https://ai.pydantic.dev/api/exceptions/testing-evals/>)
    * [ Debugging and Monitoring  ](https://ai.pydantic.dev/api/exceptions/logfire/>)
    * [ Multi-agent Applications  ](https://ai.pydantic.dev/api/exceptions/multi-agent-applications/>)
    * [ Graphs  ](https://ai.pydantic.dev/api/exceptions/graph/>)
    * [ Image and Audio Input  ](https://ai.pydantic.dev/api/exceptions/input/>)
  * [ Examples  ](https://ai.pydantic.dev/api/exceptions/examples/>)
Examples 
    * [ Pydantic Model  ](https://ai.pydantic.dev/api/exceptions/examples/pydantic-model/>)
    * [ Weather agent  ](https://ai.pydantic.dev/api/exceptions/examples/weather-agent/>)
    * [ Bank support  ](https://ai.pydantic.dev/api/exceptions/examples/bank-support/>)
    * [ SQL Generation  ](https://ai.pydantic.dev/api/exceptions/examples/sql-gen/>)
    * [ Flight booking  ](https://ai.pydantic.dev/api/exceptions/examples/flight-booking/>)
    * [ RAG  ](https://ai.pydantic.dev/api/exceptions/examples/rag/>)
    * [ Stream markdown  ](https://ai.pydantic.dev/api/exceptions/examples/stream-markdown/>)
    * [ Stream whales  ](https://ai.pydantic.dev/api/exceptions/examples/stream-whales/>)
    * [ Chat App with FastAPI  ](https://ai.pydantic.dev/api/exceptions/examples/chat-app/>)
    * [ Question Graph  ](https://ai.pydantic.dev/api/exceptions/examples/question-graph/>)
  * API Reference  API Reference 
    * [ pydantic_ai.agent  ](https://ai.pydantic.dev/api/exceptions/<../agent/>)
    * [ pydantic_ai.tools  ](https://ai.pydantic.dev/api/exceptions/<../tools/>)
    * [ pydantic_ai.common_tools  ](https://ai.pydantic.dev/api/exceptions/<../common_tools/>)
    * [ pydantic_ai.result  ](https://ai.pydantic.dev/api/exceptions/<../result/>)
    * [ pydantic_ai.messages  ](https://ai.pydantic.dev/api/exceptions/<../messages/>)
    * pydantic_ai.exceptions  [ pydantic_ai.exceptions  ](https://ai.pydantic.dev/api/exceptions/<./>) Table of contents 
      * [ exceptions  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions>)
      * [ ModelRetry  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry.message>)
      * [ UserError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError.message>)
      * [ AgentRunError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError.message>)
      * [ UsageLimitExceeded  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UsageLimitExceeded>)
      * [ UnexpectedModelBehavior  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.message>)
        * [ body  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.body>)
      * [ ModelHTTPError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError>)
        * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError.message>)
        * [ status_code  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError.status_code>)
        * [ model_name  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError.model_name>)
        * [ body  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError.body>)
      * [ FallbackExceptionGroup  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.FallbackExceptionGroup>)
    * [ pydantic_ai.settings  ](https://ai.pydantic.dev/api/exceptions/<../settings/>)
    * [ pydantic_ai.usage  ](https://ai.pydantic.dev/api/exceptions/<../usage/>)
    * [ pydantic_ai.format_as_xml  ](https://ai.pydantic.dev/api/exceptions/<../format_as_xml/>)
    * [ pydantic_ai.models  ](https://ai.pydantic.dev/api/exceptions/<../models/base/>)
    * [ pydantic_ai.models.openai  ](https://ai.pydantic.dev/api/exceptions/<../models/openai/>)
    * [ pydantic_ai.models.anthropic  ](https://ai.pydantic.dev/api/exceptions/<../models/anthropic/>)
    * [ pydantic_ai.models.cohere  ](https://ai.pydantic.dev/api/exceptions/<../models/cohere/>)
    * [ pydantic_ai.models.gemini  ](https://ai.pydantic.dev/api/exceptions/<../models/gemini/>)
    * [ pydantic_ai.models.vertexai  ](https://ai.pydantic.dev/api/exceptions/<../models/vertexai/>)
    * [ pydantic_ai.models.groq  ](https://ai.pydantic.dev/api/exceptions/<../models/groq/>)
    * [ pydantic_ai.models.mistral  ](https://ai.pydantic.dev/api/exceptions/<../models/mistral/>)
    * [ pydantic_ai.models.test  ](https://ai.pydantic.dev/api/exceptions/<../models/test/>)
    * [ pydantic_ai.models.function  ](https://ai.pydantic.dev/api/exceptions/<../models/function/>)
    * [ pydantic_ai.models.fallback  ](https://ai.pydantic.dev/api/exceptions/<../models/fallback/>)
    * [ pydantic_graph  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/graph/>)
    * [ pydantic_graph.nodes  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/nodes/>)
    * [ pydantic_graph.state  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/state/>)
    * [ pydantic_graph.mermaid  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/mermaid/>)
    * [ pydantic_graph.exceptions  ](https://ai.pydantic.dev/api/exceptions/<../pydantic_graph/exceptions/>)


Table of contents 
  * [ exceptions  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions>)
  * [ ModelRetry  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelRetry.message>)
  * [ UserError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UserError.message>)
  * [ AgentRunError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError.message>)
  * [ UsageLimitExceeded  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UsageLimitExceeded>)
  * [ UnexpectedModelBehavior  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.message>)
    * [ body  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.UnexpectedModelBehavior.body>)
  * [ ModelHTTPError  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError>)
    * [ message  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError.message>)
    * [ status_code  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError.status_code>)
    * [ model_name  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError.model_name>)
    * [ body  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.ModelHTTPError.body>)
  * [ FallbackExceptionGroup  ](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.FallbackExceptionGroup>)


  1. [ Introduction  ](https://ai.pydantic.dev/api/exceptions/<../..>)
  2. [ API Reference  ](https://ai.pydantic.dev/api/exceptions/<../agent/>)


Version
Showing documentation for the latest release [v0.0.31 2025-03-03](https://ai.pydantic.dev/api/exceptions/<https:/github.com/pydantic/pydantic-ai/releases/tag/v0.0.31>).
# `pydantic_ai.exceptions`
###  ModelRetry
Bases: `Exception[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/exceptions.html#Exception>)`
Exception raised when a tool function should be retried.
The agent will return the message to the model and ask it to try calling the function/tool again.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
22
23
24
25
26
27
28
29
30
31
32
33
```
| ```
classModelRetry(Exception):
"""Exception raised when a tool function should be retried.
  The agent will return the message to the model and ask it to try calling the function/tool again.
  """
  message: str
"""The message to return to the model."""
  def__init__(self, message: str):
    self.message = message
    super().__init__(message)

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = message

```

The message to return to the model.
###  UserError
Bases: `RuntimeError[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/exceptions.html#RuntimeError>)`
Error caused by a usage mistake by the application developer — You!
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
36
37
38
39
40
41
42
43
44
```
| ```
classUserError(RuntimeError):
"""Error caused by a usage mistake by the application developer — You!"""
  message: str
"""Description of the mistake."""
  def__init__(self, message: str):
    self.message = message
    super().__init__(message)

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = message

```

Description of the mistake.
###  AgentRunError
Bases: `RuntimeError[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/exceptions.html#RuntimeError>)`
Base class for errors occurring during an agent run.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
47
48
49
50
51
52
53
54
55
56
57
58
```
| ```
classAgentRunError(RuntimeError):
"""Base class for errors occurring during an agent run."""
  message: str
"""The error message."""
  def__init__(self, message: str):
    self.message = message
    super().__init__(message)
  def__str__(self) -> str:
    return self.message

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = message

```

The error message.
###  UsageLimitExceeded
Bases: `AgentRunError[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError> "pydantic_ai.exceptions.AgentRunError")`
Error raised when a Model's usage exceeds the specified limits.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
61
62
```
| ```
classUsageLimitExceeded(AgentRunError):
"""Error raised when a Model's usage exceeds the specified limits."""

```
  
---|---  
###  UnexpectedModelBehavior
Bases: `AgentRunError[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError> "pydantic_ai.exceptions.AgentRunError")`
Error caused by unexpected Model behavior, e.g. an unexpected response code.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
```
| ```
classUnexpectedModelBehavior(AgentRunError):
"""Error caused by unexpected Model behavior, e.g. an unexpected response code."""
  message: str
"""Description of the unexpected behavior."""
  body: str | None
"""The body of the response, if available."""
  def__init__(self, message: str, body: str | None = None):
    self.message = message
    if body is None:
      self.body: str | None = None
    else:
      try:
        self.body = json.dumps(json.loads(body), indent=2)
      except ValueError:
        self.body = body
    super().__init__(message)
  def__str__(self) -> str:
    if self.body:
      return f'{self.message}, body:\n{self.body}'
    else:
      return self.message

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = message

```

Description of the unexpected behavior.
####  body `instance-attribute`
```
body: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) | None = dumps[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/json.html#json.dumps> "json.dumps")(loads[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/json.html#json.loads> "json.loads")(body), indent=2)

```

The body of the response, if available.
###  ModelHTTPError
Bases: `AgentRunError[](https://ai.pydantic.dev/api/exceptions/<#pydantic_ai.exceptions.AgentRunError> "pydantic_ai.exceptions.AgentRunError")`
Raised when an model provider response has a status code of 4xx or 5xx.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
 91
 92
 93
 94
 95
 96
 97
 98
 99
100
101
102
103
104
105
106
107
108
109
110
111
```
| ```
classModelHTTPError(AgentRunError):
"""Raised when an model provider response has a status code of 4xx or 5xx."""
  status_code: int
"""The HTTP status code returned by the API."""
  model_name: str
"""The name of the model associated with the error."""
  body: object | None
"""The body of the response, if available."""
  message: str
"""The error message with the status code and response body, if available."""
  def__init__(self, status_code: int, model_name: str, body: object | None = None):
    self.status_code = status_code
    self.model_name = model_name
    self.body = body
    message = f'status_code: {status_code}, model_name: {model_name}, body: {body}'
    super().__init__(message)

```
  
---|---  
####  message `instance-attribute`
```
message: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>)

```

The error message with the status code and response body, if available.
####  status_code `instance-attribute`
```
status_code: int[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/functions.html#int>) = status_code

```

The HTTP status code returned by the API.
####  model_name `instance-attribute`
```
model_name: str[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/stdtypes.html#str>) = model_name

```

The name of the model associated with the error.
####  body `instance-attribute`
```
body: object[](https://ai.pydantic.dev/api/exceptions/<https:/docs.python.org/3/library/functions.html#object>) | None = body

```

The body of the response, if available.
###  FallbackExceptionGroup
Bases: `ExceptionGroup`
A group of exceptions that can be raised when all fallback models fail.
Source code in `pydantic_ai_slim/pydantic_ai/exceptions.py`
```
114
115
```
| ```
classFallbackExceptionGroup(ExceptionGroup):
"""A group of exceptions that can be raised when all fallback models fail."""

```
  
---|---  
© Pydantic Services Inc. 2024 to present 
